### ISSUE TITLE
Figure out and handle edgecase of @@__mocks_name having nil value

### ISSUE THREAD

**Issue by waterlink** [waterlink/mocks.cr#15]
While testing some stuff, today, got randomly nil errors from compiler on this class variable. Can't understand when exactly that happens: some investigation needed. Maybe `... || ""` would be fine.

**Comment by vjdhama** [comment]
I got the same error while running spec for ambience. Here's the [CI log](https://travis-ci.org/vjdhama/ambience#L3)(hope it helps).

**Comment by marceloboeira** [comment]
@vjdhama thanks

**Comment by waterlink** [comment]
@vjdhama @marceloboeira I have a feeling, that integration of `spec2` and `mocks` makes this happen, because I can't reproduce this with stdlib's `spec` and `mocks`.

**Comment by waterlink** [comment]
Oh, actually tests for `spec2-mocks.cr` fail right away. So somewhere in latest releases of either `mocks` or `spec2` there is something that introduces this problem.

**Comment by waterlink** [comment]
@vjdhama I have released 0.6.0 with fix that is working for `spec2-mocks.cr` integration test. Could you do `shards update mocks` and run your test suite?

**Comment by vjdhama** [comment]
@waterlink Sure I'll try it now.

**Comment by vjdhama** [comment]
@waterlink Works like a charm. Thanks.
