### ISSUE TITLE
can't declare class inside block

### ISSUE THREAD

**Issue by masukomi** [waterlink/mocks.cr#22]
Following the [example for testing class methods](https://github.com/waterlink/mocks.cr), My test says 

```
            Mocks.create_mock GitIntegration do
                mock self.get_log_between_tags(tag_a : String, tag_b : String)
            end
```

but using version `0.9.2` of mocks Crystal 0.18.4 (2016-06-21) says:

```
Error in macro 'create_mock' /Users/masukomi/workspace/changelog_manager/libs/mocks/macro/create_mock.cr:3, line 1:

  1.       class ::GitIntegration
  2.         @@__mocks_name = "GitIntegration"
  3.
  4.         include ::Mocks::BaseMock
  5.         mock(self.get_log_between_tags(tag_a : String, tag_b : String))
  6.       end
  7.
  8.       class ::Mocks::InstanceDoublesGitIntegration < ::Mocks::BaseDouble
  9.         @@name = "Mocks::InstanceDoublesGitIntegration"
 10.
 11.         def ==(other)
 12.           self.same?(other)
 13.         end
 14.
 15.         def ==(other : Value)
 16.           false
 17.         end
 18.
 19.         macro mock(method_spec, flag = :normal)
 20.           _mock({{method_spec}}, nil, ::GitIntegration.allocate)
 21.         end
 22.
 23.         mock(self.get_log_between_tags(tag_a : String, tag_b : String))
 24.       end
 25.

      class ::GitIntegration
            ^

can't declare class inside block
```

**Comment by waterlink** [comment]
Could you provide a link to the whole file where the fail occurs?

Mocks.create_mock call should be at global or module scope level.
masukomi notifications@github.com schrieb am Mi., 29. Juni 2016 um 1:54
PM:

**Comment by masukomi** [comment]
i had to add a .txt file extension to satisfy the file uploader on github 

i'm not sure which file you meant but here's the creat_mock.cr file 
[create_mock.cr.txt](https://github.com/waterlink/mocks.cr/files/353335/create_mock.cr.txt)

and here's my test file 
[changelog_generator_spec.cr.txt](https://github.com/waterlink/mocks.cr/files/353338/changelog_generator_spec.cr.txt)

**Comment by waterlink** [comment]
gist.github.com may work better ;)
masukomi notifications@github.com schrieb am Fr., 8. Juli 2016 um 3:23 AM:

**Comment by waterlink** [comment]
> Mocks.create_mock call should be at global or module scope level.

As I said in previous comment, `Mocks.create_mock` should be at the global or module level. So you can't put it inside of your `describe` or `it` statement. The same goes about any kind of function or block.
