### ISSUE TITLE
Understanding Registry::ObjectId comparision

### ISSUE THREAD

**Issue by notalex** [waterlink/mocks.cr#31]
I had some issues in getting this library to work within my project. I had to fix some pieces in mocks.cr source to make it work. Unfortunately I cannot provide a failing example. But I can provide some debugging data for understanding the problem.

https://github.com/waterlink/mocks.cr/blob/ac00657671a3f1e688e4a3863e5ad77b3dc97d45/src/mocks/registry.cr#L80
```crystal
def fetch(object_id, args : T, result)
  puts hash              #=> {{#<Mocks::Registry::ObjectId:0x2257680 @value=35765984_u64>, nil} => #<..
  puts object_id.inspect   #=> #<Mocks::Registry::ObjectId:0x2257620 @value=35765984_u64>
  hash.fetch({object_id, args}, ResultWrapper.new(result)).result
end
```
Here `hash` has a `Registry::ObjectId` which was created when `allow(..).to receive` was called
and `object_id` is a `Registry::ObjectId` which was created when we call the stubbed method.

Both these objects are different, hence in my project the `hash` is never able to find the stubbed object.
Wouldn't it be more appropriate if we compare `Mocks::Registry::ObjectId#value`, since it represents the actual stub?
Is there a scenario where comparing 2 different Registry::ObjectId objects useful?

**Comment by waterlink** [comment]
Hey, @notalex 

The `ObjectId` was required to make most programs with mocks.cr to compile.

When comparing values themselves – it would lead the compiler in some infinite recursion of trying to figure out all the type signatures.

But that was quite a while ago (like a year, or more), so perhaps it is not required anymore?

**Comment by notalex** [comment]
I wonder how it works for others, since ObjectId is instantiated twice.

```crystal
  class ObjectId
    def self.build(object)
      new(object.object_id)

```

When creating the mock.
```crystal
  macro mock(method, flag = :normal)
    ...
    def {{method_name}}({{method.args.splat}})
      ...
      %result = %method.call(::Mocks::Registry::ObjectId.build(self), ...
```

And when allowing the mock.
```crystal
  class Allow(T)
    ...
    def to(message)
      ...
        .store_stub(object_id, message.args, message.value)
    end
    ...
    private def object_id
      Registry::ObjectId.build(subject)
    end
  end
```

The compared ObjectId's cannot be the same. Right?
