### ISSUE TITLE
Update to work with Crystal 0.24.1

### ISSUE THREAD

**Issue by watzon** [waterlink/mocks.cr#33]
I think this is related to #32, but it seems as though this doesn't work correctly with 0.24.1. The specs are currently passing in Travis because the crystal version in 0.21. I am going to work on a PR for this if I can figure it out,  because I need a good mocking library for my tests.

**Comment by simaoneves** [comment]
Unfortunately it seems the author isn't much active lately, specially for this repo..

**Comment by watzon** [comment]
@simaoneves  I noticed that. Really sucks because spec2 with mocks is about as close as we have to rspec right now

**Comment by elliotize** [comment]
@watzon Did you ever figure out the fix? I don't want to repeat efforts if you figured it out.
