### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by rurounijones** [waterlink/mocks.cr#46]
The repository looks a bit abandoned.

There are no commits for a year, it doesn't appear to work on latest Crystal version. Some Pull Requests are waiting around for merging for a long time. would it be possible to get a comment on the status of this project and maybe possibility of giving more contributors merge permissions?

EDIT: I screwed up on @waterlink 's activity, was looking at repo and not general.

**Comment by taylorthurlow** [comment]
Yeah, it would be cool to get an update on this, even if it was "I don't have time to maintain it". That's no problem, but we should find someone to do that if we need to.

**Comment by igbanam** [comment]
Some few commits from @jerometwell brings the library up to speed with 0.34.0 https://github.com/jerometwell/mocks.cr

**Comment by rwnx** [comment]
I could definitely do with some attention on that PR, there are a few bits where I don't understand the authorial intent. Happy to help though!
