### ISSUE TITLE
Error on mocking module methods

### ISSUE THREAD

**Issue by marceloboeira** [waterlink/mocks.cr#7]
When trying to mock a static method of a module, such as:

``` crystal
module A
  def self.b
    puts "b"
  end
end

create_mock A do
  mock self.b
end

describe A do
  it "example" do
    expect(A).to have_received(self.b)
  end
end
```

Raises a macro error:

```
Error:
  class ::A
        ^
A is not a class, it's a module
```

@waterlink If you don't mind I'll try creating a pull-request later today.

**Comment by waterlink** [comment]
Sounds good to me. If you have any questions, while going through the
code-base, don't hesitate to ask.

## 

Best Regards,
Oleksii Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

**Comment by waterlink** [comment]
I have released `0.4.0` with your changes.

**Comment by marceloboeira** [comment]
@waterlink thanks!

**Comment by marceloboeira** [comment]
@waterlink I'll update the README with the instructions to mock modules.
